POST http://localhost:4002/products
Content-Type: application/json

{
    "name": "Teclado gamer kubuntu",
    "price": 539
}

###

GET http://localhost:4002/products


###

GET http://localhost:4002/products/7d154314-53b0-4db9-8b94-35b30b92114a


###

PUT http://localhost:4002/products/e6ab4f4b-0e77-41f3-999b-70d212190e97
content-type: application/json

{
    "name": "bacia azul",
    "price": 2.00
}


###

DELETE http://localhost:4002/products/cddfd3a1-7f24-44ac-8349-a48395c59faf